---
name: Container Registration

on:
  workflow_call:
    inputs:
      containerDirectory:
        description: Local directory where the DOCKERFILE is located
        required: true
        type: string
      containerName:
        description: Name of the container to register
        required: true
        type: string
      containerRepo:
        description: Name of the Docker repository for the registered container
        type: string
        required: true
      containerVersion:
        description: Release version for the container
        type: string
        required: true
    secrets:
      DOCKER_USER:
        description: username for Docker's repository
        required: true
      DOCKER_PASSWORD:
        description: password for Docker's repository

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    env:
      DOCKLE_HOST: "unix:///var/run/docker.sock"

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build the Docker image
        run: |
          docker build ${{ inputs.containerDirectory }} \
            --tag "${{ inputs.containerRepo }}/${{ inputs.containerName }}:${{ inputs.containerVersion }}" \
            --tag "${{ inputs.containerRepo }}/${{ inputs.containerName }}:latest"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ inputs.containerRepo }}/${{ inputs.containerName }}:${{ inputs.containerVersion }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Push the Docker image (version tag)
        run: |
          docker push ${{ inputs.containerRepo }}/${{ inputs.containerName }}:${{ inputs.containerVersion }}

      - name: Push the Docker image (latest tag)
        run: |
          docker push ${{ inputs.containerRepo }}/${{ inputs.containerName }}:latest
