---
name: Terraform Deploy

on:
  workflow_call:
    inputs:
      checkoutBranch:
        description: Branch or release to deploy
        required: true
        type: string
      workingDirectory:
        description: Directory containing terraform config
        required: true
        type: string

jobs:
  Build:
    environment: terraform
    runs-on: ubuntu-latest

    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:git s
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: Install terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: |
        terraform init
      working-directory: ${{ inputs.workingDirectory }}

    - name: Terraform Plan
      run: terraform plan -out main.tfplan
      working-directory: ${{ inputs.workingDirectory }}

    - name: Terraform Apply
      run: terraform apply main.tfplan
      working-directory: ${{ inputs.workingDirectory }}